name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: jrasanen/waveplus-docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy our Dockerfile into waveplus context
      run: cp Dockerfile waveplus/Dockerfile

    - name: Copy our Entrypoint into waveplus context
      run: cp entrypoint.sh waveplus/entrypoint.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./waveplus
        file: ./waveplus/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:latest
        platforms: linux/amd64,linux/arm64
